### ISSUE TITLE
Coverage report seems to not pick up generic functions

### ISSUE THREAD

**Issue by mehcode** [kennytm/cov#14]
Is this a known limitation or am I doing something wrong?

Ran 

```
cargo cov clean
cargo cov test
cargo cov report --open
```

On https://github.com/mehcode/wadatsumi

This crate seems to pick up a lot more than kcov so that's a plus (kcov misses the entire `cpu/` directory).

![screenshot from 2017-09-20 20-09-49](https://user-images.githubusercontent.com/753919/30677355-2ccf0852-9e40-11e7-8d5e-ec1906862027.png)

![screenshot from 2017-09-20 20-13-36](https://user-images.githubusercontent.com/753919/30677361-392af926-9e40-11e7-8276-0ec423a0e730.png)

It's missing files that are wholly compromised of generics and greys out code that is generics.

**Comment by kennytm** [comment]
Unfortunately this is a known limitation. 

If a generic function is never used, they are not instantiated and won't be sent to LLVM. Coverage information is generated by an LLVM pass. Since LLVM never sees these functions, they will be ignored in the coverage report. 

The only solution is to generate coverage information by rustc itself.
